// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PetStore.Infrastructure;

#nullable disable

namespace PetStore.Infrastructure.Migrations
{
    [DbContext(typeof(PetStoreContext))]
    partial class PetStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PetStore.Infrastructure.Models.CustomerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("PetStore.Infrastructure.Models.PetModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<string>("PetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("OwnerId");

                    b.ToTable("Pets", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("PetStore.Infrastructure.Models.VaccineModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Vaccines", (string)null);
                });

            modelBuilder.Entity("PetVaccine", b =>
                {
                    b.Property<Guid>("PetId")
                        .HasColumnType("uuid");

                    b.Property<int>("VaccineId")
                        .HasColumnType("integer");

                    b.HasKey("PetId", "VaccineId");

                    b.HasIndex("VaccineId");

                    b.ToTable("PetVaccines", (string)null);
                });

            modelBuilder.Entity("PetStore.Infrastructure.Models.CatModel", b =>
                {
                    b.HasBaseType("PetStore.Infrastructure.Models.PetModel");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsIndoor")
                        .HasColumnType("boolean");

                    b.ToTable("Cats", (string)null);
                });

            modelBuilder.Entity("PetStore.Infrastructure.Models.DogModel", b =>
                {
                    b.HasBaseType("PetStore.Infrastructure.Models.PetModel");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsTrained")
                        .HasColumnType("boolean");

                    b.ToTable("Dogs", (string)null);
                });

            modelBuilder.Entity("PetStore.Infrastructure.Models.PetModel", b =>
                {
                    b.HasOne("PetStore.Infrastructure.Models.CustomerModel", "Owner")
                        .WithMany("Pets")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("PetVaccine", b =>
                {
                    b.HasOne("PetStore.Infrastructure.Models.PetModel", null)
                        .WithMany()
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetStore.Infrastructure.Models.VaccineModel", null)
                        .WithMany()
                        .HasForeignKey("VaccineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PetStore.Infrastructure.Models.CatModel", b =>
                {
                    b.HasOne("PetStore.Infrastructure.Models.PetModel", null)
                        .WithOne()
                        .HasForeignKey("PetStore.Infrastructure.Models.CatModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PetStore.Infrastructure.Models.DogModel", b =>
                {
                    b.HasOne("PetStore.Infrastructure.Models.PetModel", null)
                        .WithOne()
                        .HasForeignKey("PetStore.Infrastructure.Models.DogModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PetStore.Infrastructure.Models.CustomerModel", b =>
                {
                    b.Navigation("Pets");
                });
#pragma warning restore 612, 618
        }
    }
}
